### ISSUE TITLE
main-footer hide 관련 질문드립니다.

### ISSUE THREAD

**Issue by guipokakgui** [ustraframework/ustraframework#10]
작성자(소속) : 김도윤(GSITM)

연관프로젝트 : GSC EV 프로젝트

내용 :
화면 로딩시에 main-footer 버튼의 연속클릭을 방지하고자 화면 로딩시에 main-footer 를 감추고 싶은데 
어떤 방법으로 감춰야하는지 질문드립니다.

**Comment by keymasroy** [comment]
default-loading.vue 컴포넌트를 확인해보면, this.$core.ui.progress 의 이벤트를 수신하여 로딩바 등의 제어를 수행하고 있습니다. 레이아웃 또는 특정 컴포넌트에서 동일한 방식으로 위의 이벤트를 수신하여 추가 처리를 수행하면 됩니다.

**Comment by guipokakgui** [comment]
넵 감사합니다~
