### ISSUE TITLE
SWAGGER 관련 프레임워크 설정에 대해서 문의 드립니다

### ISSUE THREAD

**Issue by kth31815** [ustraframework/ustraframework#11]
작성자(소속) : 김태훈(GSITM)

연관프로젝트 : GS RETAIL 전사 통합 상담 VOC 프로젝트

내용 :

안녕하세요 궁금한 사항이 있어서 이렇게 문의 드리게 되었습니다.

SWAGGER 에서 데이터를 주고 받을 시 아래의 사진 처럼 헤더 부분과 바디 부분을 받는 부분이 있는데, 바디만 보이도록 프레임워크 안에서 설정할 수 있는 부분이 있는지 궁금합니다.

<img width="364" alt="BODY" src="https://user-images.githubusercontent.com/24549584/142365372-aa7b0e66-13f7-4ac7-bd1e-e831cc52580c.PNG">

**Comment by ustraframework** [comment]
위의 영역은 swagger 설정과는 무관하며, API 자체가 응답 시 자체 WRAPPING을 하기 때문입니다.
http://guide.ustraframework.kro.kr/ref-doc/02/4l3Rzq1sZK6s5UQxwMIp

위의 링크 가이드에 wrapping을 제거하는 설정이 있습니다만 API에서 오류가 발생했을 경우 등은 별도 처리를 구현해야 합니다.
