### ISSUE TITLE
사용자 이력(USTRA_USR_HIST) 처리 관련 문의

### ISSUE THREAD

**Issue by sgchoi7** [ustraframework/ustraframework#12]
작성자(소속) : 최성구(GSITM)

연관프로젝트 : GSC 보너스카드 WAS 업그레이드

내용 :
 - 현재 사용자 (USTRA_USR) 변경 발생 시 변경 전 정보를 사용자 이력(USTRA_USR_HIST)에 저장하고 있는데요.
 - 사용자 변경 이력 조회 시 입력자ID, 입력자IP를 노출해 달라는 고객 Needs가 있습니다.
   (사용자 이력(USTRA_USR_HIST)에는 입력일시(INP_DTTM) 만 존재)
 - 1) 관련 내용으로 F/W 기능 개선이 가능한지?
 - 2) 1)번 사항이 어려우면, 해당 테이블에 컬럼을 alter하여 기능을 customizing을 할 수 있는지?

확인 후 답변 부탁 드립니다.

감사합니다.

**Comment by ustraframework** [comment]
사용자 이력 테이블은 입력,수정,삭제 시에 UPD_USR_ID, UPD_USR_IP에 처리자의 정보를 업데이트하고 있습니다.
해당 컬럼을 사용하시면 됩니다.

프레임워크 2.0 기준으로 2021/12/06에 사용자 이력 화면은 해당 정보를 추가할 예정입니다.
프레임워크 1.0은 화면을 직접 수정하여 컬럼을 노출할 수 있습니다.
