### ISSUE TITLE
U.STRA F/W 2.0 - Node 관련 문의

### ISSUE THREAD

**Issue by sgchoi7** [ustraframework/ustraframework#17]
작성자(소속) : 최성구(GSITM)

연관프로젝트 : GSC 보너스카드 WAS 업그레이드

내용 : 
U.STRA F/W 2.0 - Node 에서 masking-utils 등 공통 유틸리티에 추가할 내용이 있는데요.
override 할 수 있는 방법이 있을까요?

확인 부탁 드립니다.

감사합니다.

**Comment by ustraframework** [comment]
모듈 override 관련한 내용은 아래 링크 참조 하시면 됩니다.
http://guide.ustraframework.kro.kr/ref-doc/03/5KP6pIrA6dIUd116RVfr
