### ISSUE TITLE
dx-triple-phone-no-box 사용 중, 간헐적으로 첫번째 Inputbox의 값이 사라짐.

### ISSUE THREAD

**Issue by uglyjune** [ustraframework/ustraframework#18]
작성자(소속): 송재기 차장 (최준호(GSITM))

연관프로젝트: GC케어 통합관리자 BackOffice 프론트엔드

내용: 
dx-triple-phone-no-box 사용 중, 간헐적으로 첫번째 Inputbox의 값이 사라짐.

예를 들어, 사용자를 조회하여 정보를 표시하는 화면에서 해당 컴포넌트(dx-triple-phone-no-box)의 첫번째 Inputbox는 비어있고 나머지 Inputbox는 값이 채워져 있음.
해당 사항은 간헐적으로 나타나며 원인을 알 수 없음.

**Comment by keymasroy** [comment]
해당 이슈는 처리 완료되어 종료합니다.

**Comment by ustraframework** [comment]
해당 이슈 건에 대한 추가 설명입니다.
v-model 또는 prop sync 기능의 경우, 내부적으로는 비동기적으로 움직이게 되므로 잦은 value 값의 변경은 의도치 않은 동작을 발생하게 합니다.
따라 이 경우 반드시 $nextTick 과 같은 메소드 호출을 통해 동기적으로 변환하는 과정이 필요합니다.

```typescript
value = '010-1111-2222'
await this.$nextTick()
value = '010-2222-3333'
```
