### ISSUE TITLE
시스템>파일그룹관리 메뉴, 신규 작성 후 저장 시 생성 안됨.

### ISSUE THREAD

**Issue by uglyjune** [ustraframework/ustraframework#19]
* 작성자(소속) : 조대현 과장 (최준호@GSITM)

  * 연관프로젝트 : GC케어 통합관리자 BackOffice

  * 내용 :
BackOffice의 시스템>파일그룹관리 메뉴에 진입 -> 신규 버튼 클릭 후 내용 작성 -> 저장 버튼 누른 후 신규로 작성한 내용이 들어있지 않음.
http://sample-bo.ustraframework.kro.kr/system/file-grp 에서도 마찬가지로 신규 생성 안됨.
백엔드, 프론트엔드 오류 없음. DB 확인 결과 신규로 등록한 내용 없음.

**Comment by ustraframework** [comment]
2.0.44-snapshot.13 버전에서 개선 처리 되었습니다.
