### ISSUE TITLE
테스트 가이드 요청드립니다.

### ISSUE THREAD

**Issue by shinkiki** [ustraframework/ustraframework#21]
작성자(소속) : 신기범(GSITM)

연관프로젝트 : HY 파트너사 관리시스템

내용 : 서비스별 테스트 케이스를 작성했는데 서비스별로 ComponentScan이 실행되어 테스트 시간이 지연되고 있습니다.
해결방법 가이드 부탁드립니다.
![image](https://user-images.githubusercontent.com/4945018/199914050-89f533d9-3ed1-4574-9045-00e1c435e864.png)

**Comment by keymasroy** [comment]
Spring Test 시, 특정 Component를 기반으로 Configuration 구성 방법에 대해 안내 드립니다.

1. SpringBootTest 어노테이션이 존재하는 경우, Applicaiton의 설정을 찾기 위해 @SpringBootApplication 혹은 @SpringBootConfiguration 이 존재하는 클래스를 찾아 해당 설정을 사용하게 됩니다.
따라서 테스트 시에는 별도로 사용할 구동 클래스를 지정해야 합니다.
```java
@SpringBootApplication
// 공통 설정 영역만 scanning
@ComponentScan("com.gsitm.ustra.java.demo.management.bo.config")
public class TestApplication extends ServletApplicationRunner {
	public static void main(String[] args) throws IOException {
		ServletApplicationRunner.run(TestApplication.class, args);
	}
}
```
위의 TestApplication 클래스는 main 클래스를 별도의 테스트를 위해 생성한 예제입니다.
TestApplication 클래스는 @SpringBootTest 어노테이션 내에 classes 항목에 세팅하면 됩니다.
```java
@SpringBootTest(classes = { TestApplication.class })
```

2. 위의 설정으로 ComponentScan 설정이 제외되었으므로 특정 컴포넌트를 테스트 하기 위한 별도의 Configuration 클래스를 작성합니다.
```java
@TestConfiguration
public class SampleCrudServiceConfiguration {
	@Bean
	SampleCrudService sampleCrudService() {
		return new SampleCrudService();
	}
}
```
여기서는 특정 서비스 클래스를 테스트 하기 위해 Bean을 일부만 등록하였지만 의존성이 있는 다른 Bean이 있다면 추가적으로 등록해야 합니다.

추가된 Configuration을 다음과 같이 import 합니다.
```java
@EnableAutoConfiguration
@SpringBootTest(classes = { TestApplication.class })
@Import(SampleCrudServiceConfiguration.class)
public class SampleServiceTest extends UstraSpringTest {

}
```

- 참고 : https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-excluding-config

일반적으로 특정 Bean을 Spring에 등록하면서 특별한 초기 작업을 수행하지 않는다면 Component Scan은 상당히 빠르게 동작하는 작업입니다.
기본적으로 Spring 컨테이너의 구동은 일정 시간을 필요로 하며, 테스트 시에 오래 걸리는 작업을 확인하고 특정 대상 Bean을 제거하거나 설정을 변경하여 일정 기능을 제거하는 것이 더 효율적인 방법입니다.

또한 원활한 구동 성능을 향상하고 원활한 단위테스트를 생성하기 위해서는 Mocking 테스트도 고려할 필요가 있습니다.
- 참고 : https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/htmlsingle/#boot-features-testing-spring-boot-applications-mocking-beans
