### ISSUE TITLE
UstraExcelCellInfoModel Celltype 관련 문의 건

### ISSUE THREAD

**Issue by ijyang** [ustraframework/ustraframework#22]
안녕하세요.  MDX본부 에너지 사업팀 양일준 매니저입니다.

'대용량 엑셀 생성' 기능 사용시 컬럼의 celltype 설정 관련 문의를 드리려고 합니다.  

UstraExcelModel 생성시 UstraExcelCellInfoModel 의 Celltype 을 'Numeric'으로 선언 후 사용하려고 했으나, 데이터가 공백 또는 null 일 경우 'DataToExcelWebResourceConvert' 클래스의 'convert' 함수에서 'NumberFormatException : empty String' exception이 발생합니다. 

사용한 소스코드는 아래 와 같으며, 확인을 부탁 드립니다.

![20221116_151656987](https://user-images.githubusercontent.com/118334761/202099474-f7841414-26bb-4015-b523-13fd3d8893f1.jpg)

**Comment by keymasroy** [comment]
2.1.1.16-SNAPSHOT 버전에 적용되었습니다. 
프레임워크 업데이트 후 적용해보시기 바랍니다.

**Comment by keymasroy** [comment]
이슈 해결되어 클로징합니다
