### ISSUE TITLE
엑셀 다운로드 파일 - 빈값 계산 시 오류 문의 건

### ISSUE THREAD

**Issue by ijyang** [ustraframework/ustraframework#23]
안녕하세요. 에너지사업팀 양일준 매니저입니다.

USTRA 엑셀 파일 생성시 CELLTYPE을 'NUMERIC' 으로 선언할 경우, 빈값의 셀이 수식으로 처리 되지 않아 문의를 드립니다. 
아래 사진과 같이 빈값끼리 연산할 경우 값오류가 발생하고 있습니다. 확인 부탁 드립니다.

1. USTRA 엑셀 파일 
![KakaoTalk_20221118_132137987](https://user-images.githubusercontent.com/118334761/202616575-4cf5141d-eb32-4990-a8e6-9bf2331ff6b0.jpg)

2. 일반적인 엑셀 파일
![KakaoTalk_20221118_132137987_01](https://user-images.githubusercontent.com/118334761/202616622-669d1c0e-3725-4112-91b1-21e492fcf9e0.jpg)

**Comment by keymasroy** [comment]
Java Framework 2.1.1.18-SNAPSHOT 버전을 적용하시면 됩니다.
