### ISSUE TITLE
프레임워크 nginx 호환성 확인

### ISSUE THREAD

**Issue by oseongryu** [ustraframework/ustraframework#26]
작성자(소속) : 유오성(GSITM)

연관프로젝트 : 프레딧클라우드구축 프로젝트

내용 :
고객사에서 U.STRA Famework가 최신버전의 nginx를 사용하는데 문제가 없는지 확인요청이 와서
문의를 남깁니다. (U.STRA Framework 버전 2.1.2-snapshot.38)

***고객사 확인요청사항**
ISMS 수검간 결함 조치사항으로, 다음의 내용이 있습니다.
. nginx 버전이 eos 된 버전 임 : 1.20.2 -> 최신 버전 1.22~1.23
Minor Version으로 큰 문제 없을 것으로 보입니다만, 혹시 현재 운용하고 있는 프레임워크가 
위 nginx 버전에서 사용이 가능한지 여부를 확인 부탁드립니다.

**Comment by keymasroy** [comment]
안녕하세요. nginx 버전의 경우, 프레임워크를 사용하는데 문제는 없습니다.
현재 각 사이트에 1.12.x~1.22.x 버전까지 다양하게 적용되어 있습니다.
