### ISSUE TITLE
middleware.ts 관련 문의

### ISSUE THREAD

**Issue by CarrieGuts** [ustraframework/ustraframework#27]
middleware.ts에서 특정 메소드가 아니면 405 에러를 리턴하는게 있는데요.
만약 허용 메소드를 추가해 주려면 어떻게 해야하나요?

**Comment by keymasroy** [comment]
문의 하신 내용을 보니 서버미들웨어에 관한 내용인 것 같습니다.
서버 미들웨어 등록 시에 method() 구현에 따라 메소드 허용이 구분됩니다.


```typescript
import { ServerMiddleware, NextHandleFunction } from '@ustra/core/src/index.server'
import { HttpMethod } from '@ustra/core/src/server/http/const'

export class AppPropMiddleware extends ServerMiddleware<NuxtAppProperties> {
  method(_appProp: NuxtAppProperties, _buildContext?: any) {
    return [ HttpMethod.POST, HttpMethod.GET ]
  }
}
```
위의 코드와 같이 method 함수를 구현할 때 배열로 리턴을 해주시면 됩니다.
null 값을 return할 경우 any로 오픈됩니다.

관련 가이드는 아래 링크를 확인해주시면 됩니다.
http://guide.ustraframework.kro.kr/ref-doc/03/2qXAEILSBpsvFe0svhwR

**Comment by CarrieGuts** [comment]
> 문의 하신 내용을 보니 서버미들웨어에 관한 내용인 것 같습니다. 서버 미들웨어 등록 시에 method() 구현에 따라 메소드 허용이 구분됩니다.
> 
> ```ts
> import { ServerMiddleware, NextHandleFunction } from '@ustra/core/src/index.server'
> import { HttpMethod } from '@ustra/core/src/server/http/const'
> 
> export class AppPropMiddleware extends ServerMiddleware<NuxtAppProperties> {
>   method(_appProp: NuxtAppProperties, _buildContext?: any) {
>     return [ HttpMethod.POST, HttpMethod.GET ]
>   }
> }
> ```
> 
> 위의 코드와 같이 method 함수를 구현할 때 배열로 리턴을 해주시면 됩니다. null 값을 return할 경우 any로 오픈됩니다.
> 
> 관련 가이드는 아래 링크를 확인해주시면 됩니다. http://guide.ustraframework.kro.kr/ref-doc/03/2qXAEILSBpsvFe0svhwR

안녕하세요.
위와 같이 처리했는데, 아직 해당 method가 405로 표시된다면 어떤게 문제 일수 있을까요? 사용자 미들웨어를 작성하고, 해당 미들웨어를 사용한 상태입니다.

**Comment by keymasroy** [comment]
다음과 같이 미들웨어를 등록하고 테스트하였을 때 GET, POST, PATCH, PUT 등의 메소드가 모두 정상적으로 호출되는 것을 확인하였습니다.
```
import { ServerMiddleware, NextHandleFunction } from '@ustra/core/src/index.server'
import NuxtAppProperties from '@ustra/nuxt/src/config/nuxt-app-properties'
import ConnectHelper from '@ustra/core/src/server/connect-helper'

export class JsonReturnMiddleware extends ServerMiddleware {
  prefix() {
    return false
  }

  useStaticPath() {
    return false
  }

  path(_appProp: NuxtAppProperties, _buildContext?: any): string {
    return '/json-return'
  }

  handler(_appProp: NuxtAppProperties, _buildContext?: any): NextHandleFunction {
    return (_req, _res, _next) => {
      ConnectHelper.sendJson(_req, _res, { result: 'success' })
    }
  }
}
```
호출은 dev server, nuxt start node, PM2 에서 모두 정상적입니다. 405 응답이 발생된다면 앞 단의 웹 서버 등을 먼저 점검하시는게 좋을 것 같습니다.
