### ISSUE TITLE
데모 사이트 계정 잠김 해제 요청

### ISSUE THREAD

**Issue by pwjman** [ustraframework/ustraframework#28]
어떤 이유에서 그런지 모르겠는데 오후 2시반쯤 부터 갑자기 인증 시도 횟수 초과로 계정이 잠겼다고 나옵니다.
처리가 가능하실까요?

감사합니다.

**Comment by keymasroy** [comment]
조치되었습니다.

**Comment by pwjman** [comment]
대단히 감사합니다^^


옵소프트 주식회사
https://www.orbsoft.kr
(06619) 서울 서초구 서초대로 398, 6층 609호(서초동)
전화번호0507-1338-2738 핸드폰010-4226-2738
***@***.***
#웹#앱#인터넷#솔루션 @





-----Original Message-----
