### ISSUE TITLE
Framework 2.0 - Java 에서 USTRA_BAT, USTRA_BAT_INST, USTRA_BAT_HIST  Table 삭제된 이유 문의 

### ISSUE THREAD

**Issue by smjang20** [ustraframework/ustraframework#31]
안녕하세요.   Framework 2.0 - Java 소스 관련하여 문의드립니다. 

소스에는  **USTRA_BAT, USTRA_BAT_INST, USTRA_BAT_HIST**  관련된 Mapper와 Repositiory가 있고, 제어하는 Controller 도 있는 것으로 보입니다. 

하지만 DBMS에서 DDL SLQ 을 받아보면, "JAVA 2.0.20.RELEASE" 이후에 삭제되었는데,  **Table이  삭제된 이유를 문의드립니다.** 

**Batch 기능 구현을 위하여 필요없는 테이블인지 문의드립니다.** 

감사합니다.

**Comment by wisehouse** [comment]
해당 테이블은 배치 프레임워크에서 사용하던 테이블입니다. 2.0 버전 이후에 배치 프레임워크가 다시 개발되면서 사용하지 않게 되었습니다.
