### ISSUE TITLE
Vue 단 설정 파일에서 질문이 있습니다.

### ISSUE THREAD

**Issue by guipokakgui** [ustraframework/ustraframework#5]
작성자(소속) : 김도윤(GSITM)

연관프로젝트 : GSC EV 프로젝트

내용 : 
ep-auth-manager > listenGlobalEventBus() 함수가 언제 호출 되는지 알고 싶습니다.

현재 EV쪽 앱에서 간혹 발생하는 네트워크 오류 모달창이 뜨는 부분이...이쪽과 연관이 있는듯 하여 문의 드립니다.

**Comment by keymasroy** [comment]
해당 event bus는 auth-event-bus 이며, 인증에 대한 권한 없음, 인증 만료/해제 등의 상황에서 발생합니다.
해당 프로젝트는 JWT 인증을 수행하고 있으므로 서버 통신간 토큰 정보가 정상적으로 반환되지 못한 경우 발생합니다.
정확히 얘기하면 서버에서 인증이 끊겼다고 인지되는 상황입니다.

아래의 케이스에서 발생할 수 있습니다.
 1) 액세스 토큰과 리프레쉬 토큰이 모두 만료되었거나 삭제된 경우
 2) 인증 로직간 오류가 발생한 경우

사례로 보았을 때 1번의 케이스가 의심됩니다. 클라이언트에서 토큰 정보가 정상적으로 Request 되지 않는 케이스일 수 있습니다.
base1/nuxt/src/vue/plugins/auth-plugin 에서 정확히 발생되는 시점을 확인할 수 있습니다.
