### ISSUE TITLE
Vue > Loading() 관련 질문 드립니다.

### ISSUE THREAD

**Issue by guipokakgui** [ustraframework/ustraframework#8]
작성자(소속) : 김도윤(GSITM)

연관프로젝트 : GSC EV 프로젝트

내용 :
Data/화면 로딩시 사용하는 Loading() (@gsitm/nuxt/dist/vue/decorators) 쪽에서 깜빡거림 현상 있어 이 부분 관련해서 조치를 원한다는 말씀이 나와서요~ (main-menu > movePage())

혹시 이부분을 완화할수 있는 방안이 따로 있을지 궁금해서 질문드립니다.

**Comment by keymasroy** [comment]
깜빡 거리는 현상은 show hide가 자주 일어나는 현상으로 보입니다.
default-loading.vue에서  transition 태그를 사용하여 UI 적인 현상을 완화 시킬 수 있습니다.

트랜지션 사용법은 "https://nuxtjs.org/docs/features/transitions/"을 참고하시기 바랍니다.

**Comment by guipokakgui** [comment]
넵 감사합니다~
